trying to implement the zenboard sharing feature
GitHub-Campus-Experts-Unilag/DevZenBackend pull request #17
Opened 2024-10-30 15:14 UTC by Alfred-Emmanuel

I implemented the zenboard sharing feature, i need your input on whether anything is missing or not

2024-11-01 13:42 UTC, tdadadavid requested changes

2024-11-01 13:42 UTC, tdadadavid commented on src/zenboard/models/permissions.ts
> +    default: "viewer",
create a typescript enum for this you can call it `AccessLevels`

2024-11-01 13:42 UTC, tdadadavid commented on src/zenboard/routes/index.ts
> +      //   ownerId,
Why are not attaching the board to the particular user that created it.

2024-11-01 13:42 UTC, tdadadavid commented on src/zenboard/models/index.ts
> +    // ownerId: {
Why did you leave this commented out.

2024-11-01 13:42 UTC, tdadadavid commented on src/zenboard/services/permissions.ts
> +  accessLevel: "owner" | "editor" | "viewer"
Change this to a type or enum as I said earlier.

2024-11-04 20:38 UTC, Alfred-Emmanuel commented
@tdadadavid all done

2024-11-06 09:40 UTC, tdadadavid requested changes

2024-11-06 09:40 UTC, tdadadavid commented on src/auth/helpers/token.service.ts
> +  private isGoogleToken(token: string): boolean {
What is the thought process behind this?

2024-11-07 13:42 UTC, tdadadavid approved these changes

2024-11-07 13:42 UTC, merged